name: bitnami-wordpress-nginx-latest
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    debug:
      volumes:
        volume:
          mount_path: /bitnami/mariadb
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
      MARIADB_USER: bn_wordpress
      MARIADB_DATABASE: bitnami_wordpress
    reserved_name: mariadb
  wordpress:
    image: docker.io/bitnami/wordpress-nginx:latest
    interfaces:
      main:
        port: 8080
      main2:
        port: 8443
    debug:
      volumes:
        volume:
          mount_path: /bitnami/wordpress
    depends_on:
      - mariadb
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
      WORDPRESS_DATABASE_HOST: mariadb
      WORDPRESS_DATABASE_PORT_NUMBER: '3306'
      WORDPRESS_DATABASE_USER: bn_wordpress
      WORDPRESS_DATABASE_NAME: bitnami_wordpress
    reserved_name: wordpress
